version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "jest*"
          - "typescript"
          - "ts-jest"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@types/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "automated"
